### ISSUE TITLE
Issue while deploying API on remote server  (IIS)

### ISSUE THREAD

**Issue by ayushlocusnine** [aws-samples/iot-dotnet-publisher-consumer#11]
Exception Info: uPLibrary.Networking.M2Mqtt.Exceptions.MqttConnectionException: Exception connecting to the broker ---> System.ComponentModel.Win32Exception (0x8009030D): The credentials supplied to the package were not recognized at System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface secModule, String package, CredentialUse intent, SCHANNEL_CRED scc)

**Comment by sundarnarasiman** [comment]
Generally an MQTT Device Client is design to run as a background process. If you host it in IIS or any web server, the process become stateless and hence won't be able to connect to MQTT server endpoint for a longer period of time. Deploying to IIS is also out of scope of this component. If you want a web page to ingest to MQTT broker, you need to look at ingesting messages from web page using MQTT over Websockets channel. I have implemented that also. You can take a look at the below repository.

https://github.com/aws-samples/aws-iot-core-dotnet-app-mqtt-over-websockets-sigv4

Hope this helps.
