### ISSUE TITLE
unable to connect to iot 

### ISSUE THREAD

**Issue by dillipdala** [aws-samples/iot-dotnet-publisher-consumer#2]
An unhandled exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' occurred in M2Mqtt.Net.dll

the above issue is getting  when client is connecting..
 IotClient.Connect(ClientID);

please help..

**Comment by cristamd** [comment]
Note sure if this is relevant now, but I got that exception when connecting to AWS IoT if I forgot to activate my certificate for the Thing, and if I forgot to attach a security policy to the certificate. Hope that helps if you are still having problems.

**Comment by sundarnarasiman** [comment]
Does the x509 certificates have required IAM policies to connect, subscribe and publish to the IOT MQTT Topics ?

**Comment by sundarnarasiman** [comment]
> An unhandled exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' occurred in M2Mqtt.Net.dll
> 
> the above issue is getting when client is connecting..
> IotClient.Connect(ClientID);
> 
> please help..

You can enable cloud watch logs on Iot Core & see if you get any clue for troubleshooting. Make sure that that firewall is not blocking calls on port 8883 to AWS IoT End Point. Also make sure that the certificates are activated and required IAM policies are applied on the certificate.
