### ISSUE TITLE
Client disconnects when trying to subscribe

### ISSUE THREAD

**Issue by riadKasabaqi-Kuest** [aws-samples/iot-dotnet-publisher-consumer#3]
Everytime i try to subscribe to a topic (any topic) it disconnects my client.
No error is thrown from what I observed from debugging.

**Comment by sundarnarasiman** [comment]
Are you trying this behind a firewall ?. Does the x509 certificates have required IAM policies to connect, subscribe and publish to the IOT MQTT Topics ?

**Comment by sundarnarasiman** [comment]
> Everytime i try to subscribe to a topic (any topic) it disconnects my client.
> No error is thrown from what I observed from debugging.

closed
