### ISSUE TITLE
Why use the CA certificate when generating the pfx?

### ISSUE THREAD

**Issue by SelaO** [aws-samples/iot-dotnet-publisher-consumer#7]
Why did you use the CA in this command? It can also connect with pfx that isn't generated with a pfx.

`openssl pkcs12 -export -in dotnet-devicecertificate.pem -inkey dotnet-private.pem.key -out dotnet_devicecertificate.pfx -certfile root-CA.crt`

Is there any security advantage in using the CA or is it unnecessary? 

I read that the `-certfile` is optional:

https://www.openssl.org/docs/man1.0.2/man1/pkcs12.html

https://www.ssl.com/how-to/create-a-pfx-p12-certificate-file-using-openssl/

**Comment by sundarnarasiman** [comment]
If it's optional you can leave it.
